# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: get changelog
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          version: 1.0.0

      
      - name: see changelog
        run: |
          echo "${{ steps.get_release_notes.outputs.release_notes }}"
        shell: bash -ex {0}

      - name: 'Find release ID'
        id: find_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}

      - name: 'Update Release description'
        uses: irongut/editrelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ steps.find_release.outputs.id }}
          body: "Package uploaded to https://example.org\n${{ steps.get_release_notes.outputs.release_notes }}"
